INSERT INTO imports (
  instrument_id,
  source_name,
  source_hash,
  input_timezone,
  bar_interval_seconds,
  merge_policy,
  started_at_utc,
  finished_at_utc,
  ts_min_utc,
  ts_max_utc,
  row_count_read,
  row_count_inserted,
  row_count_updated,
  row_count_rejected,
  status,
  error_summary
) VALUES (
  %(instrument_id)s,
  %(source_name)s,
  %(source_hash)s,
  %(input_timezone)s,
  %(bar_interval_seconds)s,
  %(merge_policy)s,
  %(started_at_utc)s,
  NULL,
  NULL,
  NULL,
  0,
  0,
  0,
  0,
  %(status)s,
  %(error_summary)s
)
RETURNING import_id;
